import math

# 1. Noktaların Tanımlanması
points = [(1, 2), (3, 4), (5, 6), (7, 8), (2, 1)]

# 2. Öklid Mesafesi İçin Bir Fonksiyon Yazma
def euclideanDistance(point1, point2):
    """İki nokta arasındaki Öklid mesafesini hesaplar."""
    return math.sqrt((point1[0] - point2[0])**2 + (point1[1] - point2[1])**2)

# 3. Mesafelerin Hesaplanması
distances = []
for i in range(len(points)):
    for j in range(i + 1, len(points)):  # Sadece farklı nokta çiftlerini ele alıyoruz
        dist = euclideanDistance(points[i], points[j])
        distances.append(dist)

# 4. Minimum Mesafenin Bulunması
min_distance = min(distances)

# Sonuçları yazdır
print("Noktalar:", points)
print("Mesafeler:", distances)
print("Minimum Mesafe:", min_distance)
